### PR TITLE
Motion, CTF Estimation, Handedness and Tomo Reconstruction

### PR DESCRIPTION
**Pull request by fonsecareyna82**

### CODE REVIEW

**Comment by azazellochg** [comment]
Great work @fonsecareyna82 I'll try the new warp this weekend.

**Comment by azazellochg** [comment]
None of the new tests work for me. Average folder doesn't exist, no output mics exist. In the log I see:
```
2024-11-23 16:56:41.221 Received "LoadStack", with 4 arguments, for GPU #1, 23987 MB free:
2024-11-23 16:56:41.501 Loaded stack: 1950, 1950, 16, normal, real, 1 A/px, ID = -1, 1
2024-11-23 16:56:41.506 Execution took 0.279 seconds
2024-11-23 16:56:41.506 
2024-11-23 16:56:41.545 Received "MovieProcessMovement", with 2 arguments, for GPU #1, 23987 MB free:
2024-11-23 16:56:41.741 System.IO.DirectoryNotFoundException: Could not find a part of the path '/scratch/projects/ScipionUserData/projects/TestWarpMotionCorrection/Runs/000089_ProtWarpMotionCorr/extra/warp_frameseries/average/Falcon_2012_06_12-16_55_40_0_movie_motion.json'.
2024-11-23 16:56:41.741    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
2024-11-23 16:56:41.741    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
2024-11-23 16:56:41.741    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
2024-11-23 16:56:41.741    at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
2024-11-23 16:56:41.741    at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
2024-11-23 16:56:41.741    at Warp.Movie.SaveMotionTracks() in /usr/share/miniconda/envs/package-build/conda-bld/warp_1732296191863/work/WarpLib/Movie.cs:line 320
2024-11-23 16:56:41.741    at Warp.Movie.ProcessShift(Image originalStack, ProcessingOptionsMovieMovement options) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1732296191863/work/WarpLib/Movie.cs:line 2514
2024-11-23 16:56:41.741    at WarpWorker.WarpWorker.EvaluateCommand(NamedSerializableObject Command) in /usr/share/miniconda/envs/package-build/conda-bld/warp_1732296191863/work/WarpWorker/WarpWorker.cs:line 277
```

**Comment by fonsecareyna82** [comment]
I don't know what might be going on Grigory. The tests are working for us. Try deleting the “movies” test folder so that Scipion can download it again.

**Comment by fonsecareyna82** [comment]
I will update the version in the plugin

**Comment by azazellochg** [comment]
The tests are passing. However, if I try to use batch size =0 for SPA motioncor, I get:
```
00002:   Traceback (most recent call last):
00003:     File "/public/EM/Scipion/scipion-dev/scipion-pyworkflow/pyworkflow/protocol/executor.py", line 156, in run
00004:       self.step._run()  # not self.step.run() , to avoid race conditions
00005:     File "/public/EM/Scipion/scipion-dev/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 257, in _run
00006:       resultFiles = self._runFunc()
00007:     File "/public/EM/Scipion/scipion-dev/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 253, in _runFunc
00008:       return self._func(*self._args)
00009:     File "/public/EM/Scipion/scipion-dev/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 2553, in resumableStepGeneratorStep
00010:       self.stepsGeneratorStep()
00011:     File "/public/EM/Scipion/scipion-dev/scipion-em-plugins/scipion-em-warp/warp/protocols/protocol_base.py", line 410, in stepsGeneratorStep
00012:       splitMicNameList = [micNamesToProcess[i:i + batches] for i in range(0, len(micNamesToProcess), batches)]
00013:   ValueError: range() arg 3 must not be zero
```

**Comment by azazellochg** [comment]
Moreover, the threading is weird when using 3 threads on 2 GPUs. Each processMovieStep has "-device_list 0 1", while I would expect GPUs to be distributed among the threads.

**Review by azazellochg — APPROVED** [review]

**Pull request merged**
